---
title: "Using R for Computational Biology"
author: "Marc, Bronson, Debbie and Sean"
date: "3/9/2016"
output: html_document
---


# Literate programming.

Literate programming is the idea that a single document can contain both human ideas and executable machine code.  It was initially put forward by the legendary Donald Knuth.  And it is especially valuable in fields like science and mathematics where ideas need to be reproducible and testable when shared with colleagues.  Over the years there have been several attempts to make this workable and they have seen varying degrees of success, but one of the most usable and successful applications of this is the R markdown (.Rmd) document.

### What is an .Rmd file?

An R markdown (.Rmd) document allows you to embed R code right into the middle of your prose.  You can make one right from your RStudio session by simply choosing it from the File menu.  The markdown is extremely simple and easy to learn.  But for a fully detailed description of all advanced features, be sure to have a look at this document here: 
```{bash, eval=FALSE}
http://rmarkdown.rstudio.com/
```

### Reproducible research

But why would you want to do this?  Probably the best reason is that you want to know both what code you wrote and why you wrote it later on.  By documenting your code with .Rmd files, you can come back later and see both what you were thinking as well as what code you ran.  It is also a nicely explicit way of sharing workflows with colleagues who otherwise might struggle to reproduce your work.

As an example of a use case for .Rmd, all the handouts for this course were created with .Rmd documents.  Using .Rmd allowed us to run both a spelling check __and__ a code check to make sure that all the code blocks ran as expected before we went to press.

Also useful to know is that you can use .Rmd for languages other than just R.  Sure it's great for R, but you can also write code chunks that run a whole array of alternative language calls.  Have a look at this list of alternate possibilities:

```{r, echo=FALSE}
names(knitr::knit_engines$get())
```
Lets do a quick exercise to learn what markdown looks like and how you can edit it

***
####  <span style="color:blue">__Exercise R4:__</span> 

Lets start by using RStudio to create an .Rmd file.  You can do this by going to the `File` menu, and selecting `New File` followed by `R Markdown ...`.  Next you will notice that you can create many different 'flavors' of .Rmd file, for our example, just choose a basic 'Document', and fill in the title and authors.  Also choose 'HTML' as the desired output (you can change this later).

Now look at the document that is opened up in RStudio.  Notice how certain sections of it are marked by triple back ticks (```).  These are code chunks which will be evaluated when the document is rendered.  You can put whatever R code you want to into these chunks and you can surround it be whatever prose you need to include in the document.

Now add a new code chunk to the document to define and test the function you created in exercise 1.

***





# Version control.

So writing your code as .Rmd files will go a long ways towards helping you compose your ideas so that things can be tested easily.  But what if you have a lot of R code and you are making a lot of changes?  How will you keep track of what has changed?  And if you work on a piece of code with a co-worker?  How will you both be able to work on it without losing your minds?

The answer is to use version control software.  Version control software is something that all software developers use, and it's very much worth your time to learn to use it too.  It's not difficult to learn, but if you make good use of it, it can not only save your bacon, but it can make your life a lot easier as well.  There have been many popular flavors of version control software that have come out over the years.  A few you might have heard about are `rcs`, `cvs`, `svn` and more recently `git`. 

Version control is probably too big a topic to do justice to in a beginner course (it could be a short class on it's own).  But it is mentioned here so that you know it is something that you should really learn about.


***

# Homework exercises.

Some of you have been asking for homework.  One great activity is to work through external vignettes.  Some good packages to look at ahead of next week are these:

```
http://bioconductor.org/packages/release/bioc/html/ShortRead.html

http://bioconductor.org/packages/release/bioc/html/DESeq2.html

http://bioconductor.org/packages/release/bioc/html/AnnotationDbi.html

http://bioconductor.org/packages/release/bioc/html/GenomicFeatures.html
```

If you look at the .pdf files for these packages (even if you don't fully understand them) you will be helping to set yourself up for success next time.  Another thing to look is to explore the Bioconductor packages here:

```
http://bioconductor.org/packages/release/BiocViews.html#___Software
```

As you do that, pay close attention to the tree hierarchy and to the search boxes on that page.  These all allow you to search the repository in different ways until you can find a package written to solve a problems that you are working on.  Once you find software written to solve problems you are working on, you should read through the vignettes for it.



***
***
***


####  <span style="color:blue">__Exercise R4:__</span> 

Lets start by using RStudio to create an .Rmd file.  You can do this by going to the `File` menu, and selecting `New File` followed by `R Markdown ...`.  Next you will notice that you can create many different 'flavors' of .Rmd file, for our example, just choose a basic 'Document', and fill in the title and authors.  Also choose 'HTML' as the desired output (you can change this later).

Now look at the document that is opened up in RStudio.  Notice how certain sections of it are marked by triple back ticks (```).  These are code chunks which will be evaluated when the document is rendered.  You can put whatever R code you want to into these chunks and you can surround it be whatever prose you need to include in the document.

Now add a new code chunk to the document to define and test the function you created in exercise 1.

#####  <span style="color:blue">__Answer for Exercise R4:__</span> 


The code chunk that you insert into your document should look like this (minus the "|" symbol on the left hand edge of the following display).  The reason for the "|" is because it is hard to get RStudio to render what a code chunk should look like since it wants to interpret that code chunk...

````
|       ```{r}
        myPasteFun <- function(x){
          paste(x, 'extension', sep=".")
        }
        myPasteFun('testStr')
        ```
````



